name: EUVA CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore EUVA.sln

    - name: Build
      run: dotnet build EUVA.sln --configuration Release --no-restore

    - name: Execute Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish EUVA.UI/EUVA.UI.csproj -c Release -r win-x64 --self-contained false -o ./publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EUVA-Build
        path: ./publish
