name: Release App
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "categories": [
                {
                  "title": "## 🚀 New Feat",
                  "labels": ["feature"],
                  "filter": { "pattern": ".*(add|new|create|feat).*", "flags": "i" }
                },
                {
                  "title": "## 🛠 Update and improvements",
                  "labels": ["update"],
                  "filter": { "pattern": ".*(update|improve|change|refactor).*", "flags": "i" }
                },
                {
                  "title": "## 🐛 Fixed Bug",
                  "labels": ["fix"],
                  "filter": { "pattern": ".*(fix|bug|issue).*", "flags": "i" }
                },
                {
                  "title": "## 🗑 Remove",
                  "labels": ["remove"],
                  "filter": { "pattern": "^remove.*", "flags": "i" }
                }
              ],
              "template": "## What's new in EUVA?\n\n#{{CHANGELOG}}",
              "empty_template": "## What's new in EUVA?\n\nNo changes in this release.",
              "label_extractor": [
                { "pattern": "^(add|new|create|feat).*", "target": "feature", "flags": "i" },
                { "pattern": "^fix.*", "target": "fix", "flags": "i" }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          tag_name: ${{ github.ref_name }}
          draft: true